export const inquiriesData = [
  { FullName: "John Smith", Subject: "Transport timing issue", Status: "Pending", Role: "Driver", Date: "2023-03-12" },
  { FullName: "Olivia Bennett", Subject: "Bus missed my child", Status: "Pending", Role: "Parent", Date: "2022-06-27" },
  { FullName: "Daniel Warren", Subject: "Incorrect billing", Status: "Pending", Role: "Parent", Date: "2024-01-08" },
  { FullName: "Chloe Hayes", Subject: "Driver was late", Status: "Pending", Role: "Driver", Date: "2021-10-05" },
  { FullName: "Marcus Reed", Subject: "Complaint about noise", Status: "Pending", Role: "Parent", Date: "2023-02-19" },
  { FullName: "Isabelle Clark", Subject: "Bus route change", Status: "Reviewed", Role: "Guest", Date: "2022-08-30" },
  { FullName: "Lucas Mitchell", Subject: "Van not arriving", Status: "Reviewed", Role: "Van Owner", Date: "2024-04-23" },
  { FullName: "Mark Wilburg", Subject: "Payment discrepancy", Status: "Reviewed", Role: "Parent", Date: "2020-11-14" },
  { FullName: "Nicholas Agenn", Subject: "Driver behavior", Status: "Reviewed", Role: "Parent", Date: "2023-07-06" },
  { FullName: "Mia Nadin", Subject: "Feedback form submission", Status: "Reviewed", Role: "Guest", Date: "2021-12-31" },
  { FullName: "Guest", Subject: "General Inquiry", Status: "Reviewed", Role: "Admin", Date: "2024-08-10" },
  { FullName: "Janith Silva", Subject: "Lost item in van", Status: "Pending", Role: "Parent", Date: "2024-09-15" },
  { FullName: "Rashmi Perera", Subject: "Driver missed stop", Status: "Reviewed", Role: "Parent", Date: "2023-12-05" },
  { FullName: "Tharindu Fernando", Subject: "Unauthorized pickup", Status: "Pending", Role: "Driver", Date: "2024-06-17" },
  { FullName: "Shehani De Silva", Subject: "Van too full", Status: "Pending", Role: "Parent", Date: "2024-03-10" },
  { FullName: "Nipun Jayasuriya", Subject: "Late pickup", Status: "Reviewed", Role: "Driver", Date: "2023-11-01" },
  { FullName: "Amanda Weerasinghe", Subject: "Billing confusion", Status: "Pending", Role: "Parent", Date: "2022-02-20" },
  { FullName: "Dulaj Wickramasinghe", Subject: "Want new van route", Status: "Reviewed", Role: "Guest", Date: "2022-05-14" },
  { FullName: "Bhanuka Silva", Subject: "Can't access app", Status: "Reviewed", Role: "Parent", Date: "2023-04-03" },
  { FullName: "Isuri Fernando", Subject: "Wrong student listed", Status: "Pending", Role: "Admin", Date: "2024-10-11" }
];
